import React from 'react';
import type { BadgeIconKey } from '@/lib/milestones';
import {
  Heart,
  Disc3,
  Flame,
  Eye,
  Star,
  UserPlus,
  Users,
  Globe,
  LayoutGrid,
  Palette,
  Sparkles,
  Trophy,
  Pencil,
  BookOpen,
  Feather,
  Mic2,
  Radio,
  Music4,
  Compass,
  Headphones,
  ListMusic,
  Clock,
  TrendingUp,
  Zap,
  Rocket,
  Crown,
} from 'lucide-react';

export const BADGE_ICONS: Record<BadgeIconKey, React.ComponentType<{ className?: string; style?: React.CSSProperties }>> = {
  heart: Heart,
  disc: Disc3,
  flame: Flame,
  eye: Eye,
  star: Star,
  userPlus: UserPlus,
  users: Users,
  globe: Globe,
  layoutGrid: LayoutGrid,
  palette: Palette,
  sparkles: Sparkles,
  trophy: Trophy,
  pencil: Pencil,
  bookOpen: BookOpen,
  feather: Feather,
  mic: Mic2,
  radio: Radio,
  music: Music4,
  compass: Compass,
  headphones: Headphones,
  listMusic: ListMusic,
  clock: Clock,
  trendingUp: TrendingUp,
  zap: Zap,
  rocket: Rocket,
  crown: Crown,
};

/** Cosmetic rarity ramp for badge rewards - louder as the tier climbs,
 *  independent of the avatarFrame/backgroundEffect curated pools. */
export const BADGE_TIER_STYLE: Record<1 | 2 | 3 | 4, { bg: string; border: string; text: string; glow: string }> = {
  1: { bg: '#f5f0e8', border: '#a5673a', text: '#7a4a28', glow: 'none' },
  2: { bg: '#eef1f5', border: '#7a8ba3', text: '#3d4d63', glow: 'none' },
  3: { bg: '#f7f0ff', border: '#9b5de5', text: '#5b2d99', glow: '0 0 8px rgba(155,93,229,0.45)' },
  4: { bg: '#1a1a1a', border: '#ffb703', text: '#ffd166', glow: '0 0 10px rgba(255,183,3,0.6)' },
};
